name: Countries
options:
  bundleIdPrefix: com.example
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "11.0"
targets:
  Countries:
    type: application
    platform: iOS
    sources:
      - path: Countries
        excludes:
          - "Assets/*.sketch"
          - "**/.gitkeep"
    settings:
      base:
        SWIFT_VERSION: 5.0