name: Countries
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "10.0"
targets:
  Countries:
    type: application
    platform: iOS
    sources: [Countries]
    settings:
      base:
        SWIFT_VERSION: 5.0